/**
 * The line-ending law, swept rather than trusted.
 *
 * The failure this exists for: a suite that is green where it was written and
 * red on a fresh checkout, saying `SyntaxError: Invalid or unexpected token`
 * with no file, no line and no stack. It is not the tests. With
 * `core.autocrlf=true`, which is the Windows default and can come from the
 * system config, every file git materialises comes out with CRLF, and vitest
 * cannot load a `.mjs` that has CRLF in it.
 *
 * What makes it worth a test rather than a fix is where it hides. An agent, or
 * a person, who writes a file and commits it never sees this: git does not
 * rewrite a working file it has just read, so the LF the author wrote stays on
 * their disk and the CRLF conversion happens only for whoever checks the commit
 * out next. That is CI, on its first push, on the very gate the CI lane built.
 * Six worktrees all agreed the suite was green.
 *
 * `.gitattributes` is the fix. This is the guard, and it is deliberately narrow:
 * it sweeps the module files the two test runners actually load, which are the
 * files where a CRLF is fatal rather than untidy. It does not sweep the whole
 * tree, because two files under `app/e2e/sandbox/` are generated by a PowerShell
 * script that writes CRLF by default and are normalised on the way into the
 * index, so a sweep of everything would go red between a regeneration and its
 * commit, and `docs/RELEASE.md` step 6 asks for exactly that regeneration on
 * release day. A guard that fires during the runbook is a guard that gets
 * deleted.
 */

import { readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

const REPO_ROOT = join(import.meta.dirname, '..', '..');

/** The trees whose files are loaded as modules by `npm test`. */
const SWEPT = ['src', 'scripts'];

/** Nothing here is authored, so nothing here is anybody's to fix. */
const SKIP_DIRS = new Set(['node_modules', 'dist', 'target', '.git', 'gen']);

const LOADED = ['.ts', '.mjs', '.js', '.cjs'];

async function* walk(dir: string): AsyncGenerator<string> {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      yield* walk(full);
    } else if (LOADED.some((ext) => entry.name.endsWith(ext))) {
      yield full;
    }
  }
}

async function loadedFiles(): Promise<string[]> {
  const found: string[] = [];
  for (const tree of SWEPT) {
    for await (const file of walk(join(REPO_ROOT, tree))) found.push(file);
  }
  return found.sort();
}

describe('the line-ending law', () => {
  it('pins the working tree to LF in .gitattributes', async () => {
    const attributes = await readFile(join(REPO_ROOT, '.gitattributes'), 'utf8');
    // The rule that matters is the one with no extension in front of it: every
    // file, not a list somebody has to remember to add to.
    expect(attributes).toContain('* text=auto eol=lf');
  });

  it('leaves no CRLF in any file the test runner loads as a module', async () => {
    const files = await loadedFiles();
    // The control. A sweep that found nothing because it looked nowhere is the
    // failure mode this assertion exists to catch, and this suite lives beside
    // more than twenty of them.
    expect(files.length).toBeGreaterThan(20);

    const withCrlf: string[] = [];
    for (const file of files) {
      const text = await readFile(file, 'utf8');
      if (text.includes('\r\n')) withCrlf.push(file.slice(REPO_ROOT.length + 1));
    }

    // Named rather than counted, because the fix is per file and a number sends
    // the next person looking for them by hand.
    expect(withCrlf).toEqual([]);
  });
});
